name: fio-stuff-smoke-test

on:
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-smoke-test:
    name: ubuntu-smoke-test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code using action/checkout
      uses: actions/checkout@v4.1.1
    - name: Install fio via the apt package manager
      run: sudo apt update && sudo apt install -y fio
    - name: Create a test file
      run: dd if=/dev/urandom of=${GITHUB_WORKSPACE}/test-file bs=1M count=128
    - name: Run fio-stuff tests against our test file
      run: ./run_suite.sh -f ${GITHUB_WORKSPACE}/test-file -t 30
